WARRIOR.Name = "Garry"
WARRIOR.Model = "models/player/Group01/male_07.mdl"
WARRIOR.Speed = 200
WARRIOR.JumpPower = 200
WARRIOR.Health = 150
WARRIOR.Armor = 50
WARRIOR.HealthGain  = 10
WARRIOR.Weapons = {"weapon_garry1","weapon_garry2"}
WARRIOR.Lore = "As the developer of this Game he is experienced in the use of tools and able to modify the gamemode to his needs."